//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SynergyLicenseMonitor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int IntervalInSeconds {
            get {
                return ((int)(this["IntervalInSeconds"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>GENL</string>\r\n  <string>GENR</string>\r\n  <string>LD00</string>\r\n  <string" +
            ">LD02</string>\r\n  <string>LD05</string>\r\n  <string>LD06</string>\r\n  <string>LD08" +
            "</string>\r\n  <string>LD11</string>\r\n  <string>LD12</string>\r\n  <string>ODBCL</st" +
            "ring>\r\n  <string>ODBCR</string>\r\n  <string>ONET</string>\r\n  <string>PSDE</string" +
            ">\r\n  <string>PSW</string>\r\n  <string>RUN</string>\r\n  <string>WRUN</string>\r\n  <s" +
            "tring>XFSP</string>\r\n  <string>XFSV</string>\r\n  <string>GENL7</string>\r\n  <strin" +
            "g>GENR7</string>\r\n  <string>LD00_7</string>\r\n  <string>LD02_7</string>\r\n  <strin" +
            "g>LD05_7</string>\r\n  <string>LD06_7</string>\r\n  <string>LD07_7</string>\r\n  <stri" +
            "ng>LD08_7</string>\r\n  <string>LD11_7</string>\r\n  <string>LD12_7</string>\r\n  <str" +
            "ing>ONET7</string>\r\n  <string>PSDE7</string>\r\n  <string>PSW7</string>\r\n  <string" +
            ">RPTW7</string>\r\n  <string>RUN7</string>\r\n  <string>WRUN7</string>\r\n  <string>XF" +
            "SP7</string>\r\n  <string>XFSV7</string>\r\n  <string>BLSRV8</string>\r\n  <string>LMK" +
            "8</string>\r\n  <string>ODBC_8</string>\r\n  <string>PSDE8</string>\r\n  <string>PSW8<" +
            "/string>\r\n  <string>PSWB8</string>\r\n  <string>RPTW8</string>\r\n  <string>RUN8</st" +
            "ring>\r\n  <string>SC_OD8</string>\r\n  <string>SC_OR8</string>\r\n  <string>SC_SQ8</s" +
            "tring>\r\n  <string>WRUN8</string>\r\n  <string>XFSP8</string>\r\n  <string>XFSV8</str" +
            "ing>\r\n  <string>BLSRV9</string>\r\n  <string>LMK9</string>\r\n  <string>ODBC_9</stri" +
            "ng>\r\n  <string>PSDE9</string>\r\n  <string>PSW9</string>\r\n  <string>RPTW9</string>" +
            "\r\n  <string>RUN9</string>\r\n  <string>SC_MY9</string>\r\n  <string>SC_OD9</string>\r" +
            "\n  <string>SC_OR9</string>\r\n  <string>SC_SQ9</string>\r\n  <string>SDBMS9</string>" +
            "\r\n  <string>WRUN9</string>\r\n  <string>XFSP9</string>\r\n  <string>XFSV9</string>\r\n" +
            "  <string>BLS10</string>\r\n  <string>LMK10</string>\r\n  <string>PSDE10</string>\r\n " +
            " <string>PSW10</string>\r\n  <string>RPTW10</string>\r\n  <string>RUN10</string>\r\n  " +
            "<string>SCMY10</string>\r\n  <string>SCOD10</string>\r\n  <string>SCOR10</string>\r\n " +
            " <string>SCSQ10</string>\r\n  <string>SDB10</string>\r\n  <string>WRUN10</string>\r\n " +
            " <string>XFSP10</string>\r\n  <string>XFSV10</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection LicenseCodes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["LicenseCodes"]));
            }
        }
    }
}
